language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_script:
  - sh -c "mysql -e 'create database IF NOT EXISTS appsumo_challenge'"
  - npm install -g gulp

services:
  - mysql

env:
  - DATABASE_NAME=appsumo_challenge DATABASE_USERNAME=travis DATABASE_PASSWORD= GOOGLE_SECRET=shh GOOGLE_ID=shh GOOGLE_EMAIL=shh@shh.shh
