language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_script:
  - npm install -g gulp

services:
  - mysql

env:
  - DATABASE_NAME=appsumo-challenge-test DATABASE_USERNAME=travs DATABASE_PASSWORD= GOOGLE_SECRET=shh GOOGLE_ID=shh GOOGLE_EMAIL=shh@shh.shh
